/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AgentProperties, GraphEdgeSync, GraphNodeSync } from '@lanxi266/dsh-cluster-agent-fs/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636c75737465724167656e744673 {
    create: (id: string, name: string) => Promise<RemoteResult<string>>
    delete: (id: string) => Promise<RemoteResult<string>>
    openAgentSpace: (id: string) => Promise<RemoteResult<string>>
    reportBinding: (sessionId: string, agentId: string) => Promise<RemoteResult<string>>
    save: (id: string, props: AgentProperties) => Promise<RemoteResult<string>>
    syncGraph: (nodes: GraphNodeSync[], edges: GraphEdgeSync[]) => Promise<RemoteResult<number>>
  }
  interface TypertRemoteMap {
    'clusterAgentFs/create': (id: string, name: string) => Promise<RemoteResult<string>>
    'clusterAgentFs/delete': (id: string) => Promise<RemoteResult<string>>
    'clusterAgentFs/openAgentSpace': (id: string) => Promise<RemoteResult<string>>
    'clusterAgentFs/reportBinding': (sessionId: string, agentId: string) => Promise<RemoteResult<string>>
    'clusterAgentFs/save': (id: string, props: AgentProperties) => Promise<RemoteResult<string>>
    'clusterAgentFs/syncGraph': (nodes: GraphNodeSync[], edges: GraphEdgeSync[]) => Promise<RemoteResult<number>>
  }
  interface TypertRemoteNamespaceMap {
    'clusterAgentFs': TypertRemoteNamespace$636c75737465724167656e744673
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
