/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_create_parameter_0$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_create_parameter_1$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_create_result$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_delete_parameter_0$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_delete_result$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_openAgentSpace_parameter_0$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_openAgentSpace_result$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_reportBinding_parameter_0$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_reportBinding_parameter_1$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_reportBinding_result$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_save_parameter_0$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_save_parameter_1$schema = z.object({
  'name': z.string(),
  'prompt': z.string(),
  'mode': z.union([z.literal("single"), z.literal("multi"), z.literal("any")]),
  'spaceEnabled': z.boolean(),
})
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_save_result$schema = z.string()
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_syncGraph_parameter_0$schema = z.array(z.object({
  'id': z.string(),
  'agentId': z.union([z.literal(null), z.string()]),
}))
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_syncGraph_parameter_1$schema = z.array(z.object({
  'from': z.string(),
  'to': z.string(),
  'direction': z.union([z.literal("single"), z.literal("none"), z.literal("double")]),
}))
const _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_syncGraph_result$schema = z.number()

export const TYPERT = {
  package: '@lanxi266/dsh-cluster-agent-fs',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/create',
      service: 'clusterAgentFs',
      namespace: 'clusterAgentFs',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/create:id',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_create_parameter_0$schema,
          },
        },
        {
          name: 'name',
          wire: 'name',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/create:name',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_create_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/create:result',
        schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_create_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/cluster-agent-fs/src/index.ts","line":101,"column":9},
    },
    {
      id: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/delete',
      service: 'clusterAgentFs',
      namespace: 'clusterAgentFs',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/delete:id',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/delete:result',
        schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_delete_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/cluster-agent-fs/src/index.ts","line":128,"column":9},
    },
    {
      id: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/openAgentSpace',
      service: 'clusterAgentFs',
      namespace: 'clusterAgentFs',
      method: 'openAgentSpace',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/openAgentSpace:id',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_openAgentSpace_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/openAgentSpace:result',
        schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_openAgentSpace_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/cluster-agent-fs/src/index.ts","line":216,"column":9},
    },
    {
      id: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/reportBinding',
      service: 'clusterAgentFs',
      namespace: 'clusterAgentFs',
      method: 'reportBinding',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/reportBinding:sessionId',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_reportBinding_parameter_0$schema,
          },
        },
        {
          name: 'agentId',
          wire: 'agentId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/reportBinding:agentId',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_reportBinding_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/reportBinding:result',
        schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_reportBinding_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/cluster-agent-fs/src/index.ts","line":140,"column":9},
    },
    {
      id: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/save',
      service: 'clusterAgentFs',
      namespace: 'clusterAgentFs',
      method: 'save',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/save:id',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_save_parameter_0$schema,
          },
        },
        {
          name: 'props',
          wire: 'props',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs/types#AgentProperties',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_save_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/save:result',
        schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_save_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/cluster-agent-fs/src/index.ts","line":115,"column":9},
    },
    {
      id: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/syncGraph',
      service: 'clusterAgentFs',
      namespace: 'clusterAgentFs',
      method: 'syncGraph',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'nodes',
          wire: 'nodes',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/syncGraph:nodes',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_syncGraph_parameter_0$schema,
          },
        },
        {
          name: 'edges',
          wire: 'edges',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/syncGraph:edges',
            schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_syncGraph_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@lanxi266/dsh-cluster-agent-fs#clusterAgentFs/syncGraph:result',
        schema: _deepseek_ai_dsh_cluster_agent_fs_clusterAgentFs_syncGraph_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/cluster-agent-fs/src/index.ts","line":277,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Filesystem-backed Agent registry with Remote methods for the browser.",
        "summary": "Filesystem-backed Agent registry with Remote methods for the browser.",
        "tags": [],
        "jsDoc": "/** Filesystem-backed Agent registry with Remote methods for the browser. */",
        "key": "clusterAgentFs",
        "exportName": "ClusterAgentFsService",
        "members": [
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote('create') async create(id: string, name: string): Promise<string>",
            "summary": "Create an agent directory with an initial `agent.json`.",
            "jsDoc": "/**\n * Create an agent directory with an initial `agent.json`.\n * @param id - stable agent id (directory name, sanitized).\n * @param name - initial display name.\n * @returns the agent id.\n */"
          },
          {
            "kind": "method",
            "name": "save",
            "signature": "@Remote('save') async save(id: string, props: AgentProperties): Promise<string>",
            "summary": "Save agent properties into its `agent.json` (creating the dir if needed).",
            "jsDoc": "/**\n * Save agent properties into its `agent.json` (creating the dir if needed).\n * @param id - stable agent id (directory name, sanitized).\n * @param props - name, prompt, mode and space toggle to persist.\n * @returns the agent id.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') async delete(id: string): Promise<string>",
            "summary": "Delete an agent directory and its contents.",
            "jsDoc": "/**\n * Delete an agent directory and its contents.\n * @param id - stable agent id (directory name, sanitized).\n * @returns the agent id.\n */"
          },
          {
            "kind": "method",
            "name": "reportBinding",
            "signature": "@Remote('reportBinding') async reportBinding(sessionId: string, agentId: string): Promise<string>",
            "summary": "Record which Agent class a running instance (session) belongs to.",
            "jsDoc": "/**\n * Record which Agent class a running instance (session) belongs to.\n * @param sessionId - the instance's session id.\n * @param agentId - the Agent class id.\n * @returns the session id.\n */"
          },
          {
            "kind": "method",
            "name": "classOf",
            "signature": "classOf(sessionId: string): string | null",
            "summary": "Resolve an instance's Agent class, or null when unbound.",
            "jsDoc": "/**\n * Resolve an instance's Agent class, or null when unbound.\n * @param sessionId - the instance's session id.\n * @returns the Agent class id, or null.\n */"
          },
          {
            "kind": "method",
            "name": "listAgents",
            "signature": "async listAgents(): Promise<Array<{ id: string } & AgentProperties>>",
            "summary": "List the Agent classes on disk (each directory under the cluster-agents root with a readable `agent.json`): directory id + persisted name/prompt.",
            "jsDoc": "/**\n * List the Agent classes on disk (each directory under the cluster-agents\n * root with a readable `agent.json`): directory id + persisted name/prompt.\n * @returns one entry per class; empty when the root is missing.\n */"
          },
          {
            "kind": "method",
            "name": "classMeta",
            "signature": "classMeta(agentId: string): AgentProperties | null",
            "summary": "Read an Agent class's persisted properties (`agent.json`), or null when the file is missing or malformed.",
            "jsDoc": "/**\n * Read an Agent class's persisted properties (`agent.json`), or null when the\n * file is missing or malformed. Synchronous so prompt-assembly providers can\n * resolve a class's persona without yielding.\n * @param agentId - the Agent class id.\n * @returns the persisted name + prompt, or null.\n */"
          },
          {
            "kind": "method",
            "name": "agentDirPath",
            "signature": "agentDirPath(agentId: string): string",
            "summary": "The absolute on-disk directory of an Agent class (its \"space\").",
            "jsDoc": "/**\n * The absolute on-disk directory of an Agent class (its \"space\").\n * @param agentId - the Agent class id.\n * @returns the absolute directory path.\n */"
          },
          {
            "kind": "method",
            "name": "openAgentSpace",
            "signature": "@Remote('openAgentSpace') async openAgentSpace(id: string): Promise<string>",
            "summary": "Open an Agent class's directory in the operating system file explorer.",
            "jsDoc": "/**\n * Open an Agent class's directory in the operating system file explorer.\n * @param id - stable agent id (directory name, sanitized).\n * @returns the opened absolute directory path.\n */"
          },
          {
            "kind": "method",
            "name": "className",
            "signature": "className(agentId: string): string",
            "summary": "Resolve an Agent class's display name, or \"default\" when unknown/missing.",
            "jsDoc": "/**\n * Resolve an Agent class's display name, or \"default\" when unknown/missing.\n * @param agentId - the Agent class id.\n * @returns the display name (fallback \"default\").\n */"
          },
          {
            "kind": "method",
            "name": "touch",
            "signature": "touch(sessionId: string): void",
            "summary": "Record cluster activity for an instance.",
            "jsDoc": "/**\n * Record cluster activity for an instance.\n * @param sessionId - the instance's session id.\n */"
          },
          {
            "kind": "method",
            "name": "lastActiveAt",
            "signature": "lastActiveAt(sessionId: string): number | null",
            "summary": "The instance's last cluster-activity time, or null when unknown.",
            "jsDoc": "/**\n * The instance's last cluster-activity time, or null when unknown.\n * @param sessionId - the instance's session id.\n * @returns epoch ms, or null.\n */"
          },
          {
            "kind": "method",
            "name": "allowFlow",
            "signature": "allowFlow(from: string, to: string): boolean",
            "summary": "Whether the canvas graph allows `from → to` (self-flow always allowed).",
            "jsDoc": "/**\n * Whether the canvas graph allows `from → to` (self-flow always allowed).\n * @param from - source Agent class id.\n * @param to - target Agent class id.\n * @returns true when the flow is allowed.\n */"
          },
          {
            "kind": "method",
            "name": "syncGraph",
            "signature": "@Remote('syncGraph') async syncGraph(nodes: GraphNodeSync[], edges: GraphEdgeSync[]): Promise<number>",
            "summary": "Replace the synced canvas graph: nodes (id + class) and edges (flow policy).",
            "jsDoc": "/**\n * Replace the synced canvas graph: nodes (id + class) and edges (flow policy).\n * @param nodes - node id → Agent class bindings.\n * @param edges - directed flow edges.\n * @returns the number of synced edges.\n */"
          }
        ],
        "types": [
          {
            "name": "AgentMode",
            "declaration": "export type AgentMode = 'single' | 'multi' | 'any';"
          },
          {
            "name": "AgentProperties",
            "declaration": "export interface AgentProperties {\n    name: string;\n    prompt: string;\n    mode: AgentMode;\n    spaceEnabled: boolean;\n}"
          },
          {
            "name": "GraphEdgeSync",
            "declaration": "export interface GraphEdgeSync {\n    from: string;\n    to: string;\n    direction: 'none' | 'single' | 'double';\n}"
          },
          {
            "name": "GraphNodeSync",
            "declaration": "export interface GraphNodeSync {\n    id: string;\n    agentId: string | null;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
